language: ruby
rvm:
  - 2.1.7

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - mkdir tmp
  - psql -c 'create database travis_ci_test' -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:schema:load
  - bundle exec rspec spec/