default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: twitter_bot_development
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

test:
  <<: *default
  database: twitter_bot_test
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: twitter_bot_production
  pool: 5
