default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

development:
  <<: *default
  database: twitter_bot_development

test:
  <<: *default
  database: twitter_bot_test

production:
  adapter: postgresql
  encoding: unicode
  database: twitter_bot_production
  pool: 5
