development:
  adapter: postgresql
  host:    localhost
  encoding: unicode
  database: twitter_bot_development
  pool: 5
  username: felix
  password: gbjrfnvi58tjvj569f

test:
  adapter: postgresql
  encoding: unicode
  database: twitter_bot_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: twitter_bot_production
  pool: 5
